[package]
name = "target_proximity_game"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
reqwest = {version="0.11.18", features=["json"]}
tokio = {version="1.31.0", features=["full"]}
